pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('NodeVersion') {
      steps {
        sh 'node --version'
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
  }
}
