pipeline {
  agent any
    stages {
    stage('Install Node.js') {
      steps {
        script {
          sh 'curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
          sh 'sudo apt-get install -y nodejs'
        }
      }
    }
        stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
        }
    }
}
