pipeline {
    agent any
    tools {
        nodejs 'your_nodejs_tool_name'
    }
    stages {
        stage('Build') {
      steps {
        sh 'npm install'
      }
        }
    // Other stages...
    }
}
